### ISSUE TITLE
Unable to cancel shipment

### ISSUE THREAD

**Issue by jschram** [SendCloud/SendCloud-API-PHP-Wrapper#14]
When I try to cancel a shipment I get the following error: 
```
{
  "error": {
    "request": "api/v2/parcels/1234567",
    "code": 405,
    "message": "Method \"DELETE\" not allowed."
  }
}
```
_(Obviously, I've removed the id of the parcel)_

I'm calling the DELETE method on the mentioned request. Shouldn't this be possible?

**Comment by Ecno92** [comment]
Canceling shipments is only possible through the SendCloud Panel web interface. It may become supported through the API in the future, but for now using the browser is the only way to cancel a shipment.

**Comment by jschram** [comment]
Good to know. Please update the API documentation accordingly, as it still mentions support for DELETE on the Parcels resource:
![image](https://cloud.githubusercontent.com/assets/10851379/22470928/1a046198-e7d1-11e6-9c17-1b4a2c73e41e.png)

**Comment by Ecno92** [comment]
@jschram Thanks for your feedback. I've registered an internal issue to get it fixed in the near future. :smiley:
