### ISSUE TITLE
Deprecated - no alternatives

### ISSUE THREAD

**Issue by mrquincle** [SendCloud/SendCloud-API-PHP-Wrapper#21]
This "Official SendCloud API PHP Wrapper" is deprecated. A question to the helpdesk - as indicated in this README file - will give you a templated answer where you will be referred to https://support.sendcloud.com/hc/nl/articles/360024967012-API-documentatie where you will be directed to https://github.com/SendCloud/SendCloud-API-PHP-Wrapper again.

**Comment by erickwilder** [comment]
Thanks for pointing out the incorrect link in our support page. Our API supports automation of many workflows for merchants. The deprecation applies just to this PHP API wrapper, not the API
